name: 03 Terraform Dev Image

on:
  workflow_dispatch: {}
  push:
    branches: [ feature/* ]
    paths:
    - terraform/Dockerfile
    - .github/workflows/terraform-images.yml
  pull_request:
    branches: [ develop ]
    paths:
    - terraform/*

env:
  REGISTRY: norseto
  TEST_REGISTRY: norseto/test
  DOCKERFILE: ./terraform/Dockerfile

jobs:
  path-context:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - [ "dev-terraform", "latest,0.13",      "TERRAFORM_VERSION=0.13.5"]
        - [ "dev-terraform", "gcp,0.13-gcp",     "TERRAFORM_VERSION=0.13.5,BASECONTAINER=dev-base:gcp"]
        - [ "dev-terraform", "aws,0.13-aws",     "TERRAFORM_VERSION=0.13.5,BASECONTAINER=dev-base:aws"]
        - [ "dev-terraform", "azure,0.13-azure", "TERRAFORM_VERSION=0.13.5,BASECONTAINER=dev-base:azure"]
        - [ "dev-terraform", "azure,0.13-full",  "TERRAFORM_VERSION=0.13.5,BASECONTAINER=dev-base:full"]
    steps:
    - uses: actions/checkout@v2
    - id: imagetag
      name: Determine Target
      run: |
        echo ::set-output name=dockerfile::${DOCKERFILE}
        MAIN=$(echo "${GITHUB_REF}" | grep -e "/main$">/dev/null; echo $?)
        if [ $MAIN -eq 1 ] ; then
          TAG=$(echo ${{ matrix.target[1] }} | awk -F, '{for (i=1; i<=NF; i++){printf("${{ matrix.target[0] }}-%s,", $i);}}' | sed -e 's/,$//')
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=repository::${TEST_REGISTRY}
          echo ::set-output name=cache::${TEST_REGISTRY}:${{ matrix.target[0] }}-${{ matrix.target[1] }}
        else
          echo ::set-output name=repository::${REGISTRY}/${{ matrix.target[0] }}
          echo ::set-output name=tag::${{ matrix.target[1] }}
          echo ::set-output name=cache::""
        fi
        if [ ${GITHUB_EVENT_NAME} = "push" ] || [ ${GITHUB_EVENT_NAME} = "workflow_dispatch" ] ; then
          echo ::set-output name=pushimg::true
        else
          echo ::set-output name=pushimg::false
        fi
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        path: .
        repository: ${{ steps.imagetag.outputs.repository }}
        dockerfile: ${{ steps.imagetag.outputs.dockerfile }}
        tags: ${{ steps.imagetag.outputs.tag }}
        build_args: ${{ matrix.target[2] }}
        push: ${{ steps.imagetag.outputs.pushimg }}
        cache_froms: ${{ steps.imagetag.outputs.cache }}

